apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tke-business-controller.fullname" . }}
  labels:
    {{- include "tke-business-controller.labels" . | nindent 4 }}
data:
  tke-business-controller.toml: |
    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [client]

      [client.business]
      api_server = "https://tke-business-api"
      api_server_client_config = "/app/conf/tke-business-api/tke-business-config.yaml"

      [client.platform]
      api_server = "https://tke-platform-api"
      api_server_client_config = "/app/conf/tke-platform-api/tke-platform-config.yaml"

    {{- if .Values.auth.enabled }}
      [client.auth]
      api_server = "https://tke-auth-api"
      api_server_client_config = "/app/conf/tke-auth-api/tke-auth-config.yaml"
    {{- end }}

    {{- if .Values.registry.enabled }}
      [client.registry]
      api_server = "https://tke-registry-api"
      api_server_client_config = "/app/conf/tke-registry-api/tke-registry-config.yaml"
    {{- end }}
