apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tke-platform-controller.fullname" . }}
  labels:
    {{- include "tke-platform-controller.labels" . | nindent 4 }}
data:
  tke-platform-controller.toml: |
    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [client]

      [client.platform]
      api_server = "https://tke-platform-api"
      api_server_client_config = "/app/conf/tke-platform-api/tke-platform-config.yaml"

    [registry]
    container_domain = "{{ .Values.registry.domain }}"
    container_namespace = "{{ .Values.registry.namespace }}"

    [features]
    monitor_storage_type = "{{ .Values.monitor.storageType }}"
    monitor_storage_addresses = "{{ .Values.monitor.storageAddress }}"