apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tke-platform-controller.fullname" . }}
  labels:
    {{- include "tke-platform-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tke-platform-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timstamp: "{{ date "20060102150405" .Release.Time }}"
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "tke-platform-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tke-platform-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - command:
            - sh
            - -c
            - cp -r /data/res /app/provider/baremetal/
          image: "{{ .Values.registryPrefix }}/{{ .Values.providerRes.repository }}:{{ .Values.providerRes.tag }}"
          imagePullPolicy: {{ .Values.providerRes.pullPolicy }}
          name: provider-res
          volumeMounts:
            - mountPath: /app/provider/baremetal
              name: provider-volume
        - name: init
          image: {{ .Values.registryPrefix }}/toolbox:v0.1.0
          command: ['sh', '-c', 'until curl -k https://tke-platform-api; do echo waiting for tke-platform-api; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.registryPrefix }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -C=/app/conf/tke-platform-controller.toml
          ports:
            - name: https
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
          volumeMounts:
            - name: {{ include "tke-platform-controller.fullname" . }}
              mountPath: /app/conf
            - name: {{ .Values.certsName }}
              mountPath: /app/certs
            - name: tke-platform-api-config
              mountPath: /app/conf/tke-platform-api
            - name: provider-config
              mountPath: /app/provider/baremetal/conf/
            - name: docker-volume
              mountPath: /app/provider/baremetal/conf/docker/
            - name: kubelet-volume
              mountPath: /app/provider/baremetal/conf/kubelet/
            - name: kubeadm-volume
              mountPath: /app/provider/baremetal/conf/kubeadm/
            - name: gpu-manifests-volume
              mountPath: /app/provider/baremetal/manifests/gpu/
            - name: gpu-manager-manifests-volume
              mountPath: /app/provider/baremetal/manifests/gpu-manager/
            - name: keepalived-manifests-volume
              mountPath: /app/provider/baremetal/manifests/keepalived/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "tke-platform-controller.fullname" . }}
          configMap:
            name: {{ include "tke-platform-controller.fullname" . }}
        - name: {{ .Values.certsName }}
          secret:
            secretName: {{ .Values.certsName }}
        - name: tke-platform-api-config
          configMap:
            name: tke-platform-api-config
        - name: provider-volume
          emptyDir: {}
        - name: provider-config
          configMap:
            name: provider-config
        - name: docker-volume
          configMap:
            name: docker
        - name: kubelet-volume
          configMap:
            name: kubelet
        - name: kubeadm-volume
          configMap:
            name: kubeadm
        - name: gpu-manifests-volume
          configMap:
            name: gpu-manifests
        - name: gpu-manager-manifests-volume
          configMap:
            name: gpu-manager-manifests
        - name: keepalived-manifests-volume
          configMap:
            name: keepalived-manifests