apiVersion: v1
kind: Secret
metadata:
  name: certs
  labels:
  {{- include "base.labels" . | nindent 4 }}
data:
  ca.crt: {{ required ".Values.caCert is required!" .Values.caCert | b64enc}}
  ca.key: {{ required ".Values.cakey is required!" .Values.caKey | b64enc}}
  server.crt: {{ required ".Values.serverCert is required!"  .Values.serverCert | b64enc }}
  server.key: {{ required ".Values.serverKey is required!" .Values.serverKey | b64enc }}
  {{- with .Values.frontProxyCACert }}
  front-proxy-ca.crt: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.oidcCACert }}
  oidc-ca.crt: {{ . | b64enc }}
  {{- end}}
  etcd-ca.crt: {{ required ".Values.etcd.caCert is required!" .Values.etcd.caCert | b64enc}}
  etcd-client.crt: {{ required ".Values.etcd.clientCert is required!"  .Values.etcd.clientCert | b64enc }}
  etcd-client.key: {{ required ".Values.etcd.clientKey is required!" .Values.etcd.clientKey | b64enc }}
