apiVersion: v1
kind: Service
metadata:
  name: {{.Values.etcdName}}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: https
      port: 2379
      protocol: TCP
      targetPort: 2379
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd
  labels:
  {{- include "base.labels" . | nindent 4 }}
subsets:
  - addresses:
      {{- range required "A valid .Values.hosts is required!" .Values.etcd.hosts }}
      - ip: {{ . | quote }}
      {{- end }}
    ports:
      - name: https
        port: {{ .Values.etcd.port }}
        protocol: TCP
