apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tke-notify-controller.fullname" . }}
  labels:
    {{- include "tke-notify-controller.labels" . | nindent 4 }}
data:
  tke-notify-controller.toml: |
    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [client]

      [client.notify]
      api_server = "https://tke-notify-api"
      api_server_client_config = "/app/conf/tke-notify-api/tke-notify-config.yaml"