apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
data:
  ca.crt: {{ required ".Values.caCert is required!" .Values.caCert | b64enc}}
  client.crt: {{ required ".Values.clientCert is required!"  .Values.clientCert | b64enc }}
  client.key: {{ required ".Values.clientKey is required!" .Values.clientKey | b64enc }}