apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: https
      port: 2379
      protocol: TCP
      targetPort: 2379
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
  {{- include "etcd.labels" . | nindent 4 }}
subsets:
  - addresses:
      {{- range required "A valid .Values.hosts is required!" .Values.hosts }}
      - ip: {{ . | quote }}
      {{- end }}
    ports:
      - name: https
        port: {{ .Values.port }}
        protocol: TCP
