apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tke-monitor-controller.fullname" . }}
  labels:
    {{- include "tke-monitor-controller.labels" . | nindent 4 }}
data:
  tke-monitor-controller.toml: |
    monitor_config = "/app/conf/tke-monitor-config.yaml"

    [secure_serving]
    tls_cert_file = "/app/certs/server.crt"
    tls_private_key_file = "/app/certs/server.key"

    [client]

      [client.monitor]
      api_server = "https://tke-monitor-api"
      api_server_client_config = "/app/conf/tke-monitor-api/tke-monitor-config.yaml"

      {{- if .Values.business.enabled }}
      [client.business]
      api_server = "https://tke-business-api"
      api_server_client_config = "/app/conf/tke-business-api/tke-business-config.yaml"
      {{- end }}

      [client.platform]
      api_server = "https://tke-platform-api"
      api_server_client_config = "/app/conf/tke-platform-api/tke-platform-config.yaml"


    [registry]
    container_domain = "{{ .Values.registry.domain }}"
    container_namespace = "{{ .Values.registry.namespace }}"

    [features]
    monitor_storage_type = "{{ .Values.monitor.storageType }}"
    monitor_storage_addresses = "{{ .Values.monitor.storageAddress }}"

  tke-monitor-config.yaml: |
    apiVersion: monitor.config.tkestack.io/v1
    kind: MonitorConfiguration
    storage:
    {{- if eq .Values.monitor.storageType "influxdb" }}
      influxDB:
        servers:
          - address: {{ .Values.monitor.storageAddress }}
            username: {{ .Values.monitor.storageUsername }}
            password: {{ .Values.monitor.storagePassword }}
            timeoutSeconds: 10
    {{- end }}
    {{- if eq .Values.monitor.storageType "elasticsearch" }}
      elasticSearch:
        servers:
          - address: {{ .Values.monitor.storageAddress }}
            username: {{ .Values.monitor.storageUsername }}
            password: {{ .Values.monitor.storagePassword }}
  {{- end }}