name: release

on:
  repository_dispatch:
    types: [release]

jobs:
  release:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          export VERSION=${{ github.event.client_payload.version }}
          make release
          make release-test